// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDespesaApi.Base;

#nullable disable

namespace RegistroDespesaApi.Migrations
{
    [DbContext(typeof(RegistroDespesaDbContext))]
    partial class RegistroDespesaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroDespesaApi.Models.Despesa", b =>
                {
                    b.Property<Guid>("codDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDespesa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDespesa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("codDespesa");

                    b.ToTable("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
